# Generated by Django 6.0 on 2026-03-27 18:00

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_update_osm_oauth2_provider'),
    ]

    operations = [
        TrigramExtension(),
    ]
